// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-dmfKFkFanL4sr9PbUpyrG3VE210w2nw',
    appId: '1:997649098916:web:966bbdd19f202968a19e31',
    messagingSenderId: '997649098916',
    projectId: 'smartpay-ad560',
    authDomain: 'smartpay-ad560.firebaseapp.com',
    storageBucket: 'smartpay-ad560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIkG04NhDT87LhtgWy3_wE0iNCvHHno1I',
    appId: '1:997649098916:android:5d10c9d475ca6c43a19e31',
    messagingSenderId: '997649098916',
    projectId: 'smartpay-ad560',
    storageBucket: 'smartpay-ad560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvSCUXyaS7GJ8vR-SeIv1HXIBsT4nIsxs',
    appId: '1:997649098916:ios:e9a66da3b13760e4a19e31',
    messagingSenderId: '997649098916',
    projectId: 'smartpay-ad560',
    storageBucket: 'smartpay-ad560.firebasestorage.app',
    iosBundleId: 'com.example.smartpay',
  );
}
